version: '3'
services:
  bot:
    build: .
    container_name: telegram_bot
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:qaz123@db:5432/finance_data
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:16.4
    environment:
      POSTGRES_DB: finance_data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qaz123
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
